server:
  port: 8081
spring:
  datasource:
    username: root
    password: agytorudhcv11
    url: jdbc:mysql://localhost:3306/xiyou3g_im?characterEncoding=utf8

  redis:
    port: 6379
    database: 1
    host: localhost
